language: c

install:
 - sudo apt-get install libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 zip unzip
 - wget https://dl.dropboxusercontent.com/u/76035852/sm-dev.zip
 - unzip sm-dev.zip
 - chmod +x sm-dev/addons/sourcemod/scripting/spcomp

script:
 - PATH+=":$PWD/sm-dev/addons/sourcemod/scripting"
 - make