sudo: false

addons:
    apt_packages:
        - lib32stdc++6  # needed for spcomp

env:
    - SMVERSION=1.7

before_script:
    # install smbuilder
    - git clone https://github.com/splewis/sm-builder
    - cd sm-builder
    - pip install --user -r requirements.txt
    - python setup.py install --prefix=~/.local
    - cd ..

    # install the sourcemod compiler
    - SMPATTERN="http:.*sourcemod-.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/$SMVERSION/"
    - SMPACKAGE=`elinks -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - TEST_SCRIPT="tests/test_compile-all.sp"

    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp -R scripting/ addons/sourcemod/
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"
    - cd ../../..

script:
    - smbuilder --flags="-E"

notifications:
    email: false
