language: c

install:
    - sudo apt-get update
    - sudo apt-get install -y gcc-multilib lynx git lib32stdc++6
    - git clone https://github.com/splewis/sm-builder
    - cd sm-builder
    - sudo pip install -r requirements.txt
    - sudo python setup.py install
    - cd ..

before_script:
    - wget http://y4kstudios.com/sourcemod/mirror/sourcemod-1.7.0-linux.tar.gz
    - tar -xzf sourcemod-1.7.0-linux.tar.gz
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"
    - cd ../../..

script:
    - smbuilder
